import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { config } from '../gateway/config.js';
import { Store } from '../data/storage/database.js';
import { initAuth } from '../security/auth/schema.js';
import { AuthService, GLOBAL_ADMIN_CODE } from '../security/auth/service.js';
import { totpCode } from '../security/auth/crypto.js';

test('native admin bootstraps once and approves a new user with password and 2FA', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'iris-users-'));
  const original = { AUTH_MODE: config.AUTH_MODE, IRIS_ADMIN_EMAIL: config.IRIS_ADMIN_EMAIL, IRIS_ADMIN_FIRST_PASSWORD: config.IRIS_ADMIN_FIRST_PASSWORD, LUMINA_ENCRYPTION_KEY: config.LUMINA_ENCRYPTION_KEY };
  Object.assign(config, { AUTH_MODE: 'native', IRIS_ADMIN_EMAIL: 'admin@example.test', IRIS_ADMIN_FIRST_PASSWORD: 'Initial#1234', LUMINA_ENCRYPTION_KEY: '4'.repeat(64) });
  const store = new Store('', directory); await store.init();
  t.after(async () => { await store.close(); rmSync(directory, { recursive: true, force: true }); Object.assign(config, original); });
  await initAuth(store); await initAuth(store);
  const service = new AuthService(store);
  const admin = await service.login(GLOBAL_ADMIN_CODE, 'Initial#1234', '');
  assert.ok('token' in admin);
  if (!('token' in admin)) return;
  assert.equal(admin.user.must_change_password, true);
  const changed = await service.changePassword(admin, 'Initial#1234', 'Updated#1234');
  const setup = await service.setup(GLOBAL_ADMIN_CODE);
  const elevated = await service.enable(changed, totpCode(setup.secret));
  assert.equal(elevated.elevated, true);
  const request = await service.requestAccess('Pessoa Teste', 'person@example.test', 'direito', ['direito']);
  const requests = await service.requests();
  const pending = requests[0] as unknown as { id: string; request_code: string };
  assert.equal(pending.request_code, request.request_code);
  const approved = await service.decide(pending.id, true, ['direito'], GLOBAL_ADMIN_CODE, '');
  assert.ok('activation_token' in approved);
  if (!('activation_token' in approved) || !('user_code' in approved)) return;
  const artifact = await service.activate(String(approved.user_code), String(approved.activation_token), 'Member#1234');
  await service.activate2fa(String(approved.user_code), String(approved.activation_token), totpCode(artifact.secret));
  const user = await service.user((await service.row(String(approved.user_code)))!);
  assert.deepEqual(user.scopes, ['direito']);
  assert.equal(user.two_factor_enabled, true);
});
